# Generated by Django 3.1.2 on 2021-04-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
