# Generated by Django 3.1.2 on 2021-04-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20210410_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/emp'),
        ),
    ]
