# Generated by Django 3.1.2 on 2021-04-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_auto_20210410_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Terminated'), ('3', 'Temporary'), ('4', 'On Notice Period')], max_length=30),
        ),
    ]
